// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package ipc_types

import (
	"fmt"
	"io"
	"sort"

	address "github.com/filecoin-project/go-address"
	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
	big "math/big"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = sort.Sort

var lengthBufIPCAddress = []byte{130}

func (t *IPCAddress) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufIPCAddress); err != nil {
		return err
	}

	// t.SubnetID (ipc_types.SubnetID) (struct)
	if err := t.SubnetID.MarshalCBOR(w); err != nil {
		return err
	}

	// t.RawAddress (address.Address) (struct)
	if err := t.RawAddress.MarshalCBOR(w); err != nil {
		return err
	}
	return nil
}

func (t *IPCAddress) UnmarshalCBOR(r io.Reader) error {
	*t = IPCAddress{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.SubnetID (ipc_types.SubnetID) (struct)

	{

		if err := t.SubnetID.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.SubnetID: %w", err)
		}

	}
	// t.RawAddress (address.Address) (struct)

	{

		if err := t.RawAddress.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.RawAddress: %w", err)
		}

	}
	return nil
}

var lengthBufSubnetID = []byte{130}

func (t *SubnetID) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufSubnetID); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Parent (string) (string)
	if len(t.Parent) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.Parent was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.Parent))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.Parent)); err != nil {
		return err
	}

	// t.Actor (address.Address) (struct)
	if err := t.Actor.MarshalCBOR(w); err != nil {
		return err
	}
	return nil
}

func (t *SubnetID) UnmarshalCBOR(r io.Reader) error {
	*t = SubnetID{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Parent (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.Parent = string(sval)
	}
	// t.Actor (address.Address) (struct)

	{

		if err := t.Actor.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Actor: %w", err)
		}

	}
	return nil
}

var lengthBufTokenAmount = []byte{129}

func (t *TokenAmount) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufTokenAmount); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Atto (big.Int) (struct)
	{
		if err := cbg.CborWriteHeader(w, cbg.MajTag, 2); err != nil {
			return err
		}
		var b []byte
		if t.Atto != nil {
			b = t.Atto.Bytes()
		}

		if err := cbg.CborWriteHeader(w, cbg.MajByteString, uint64(len(b))); err != nil {
			return err
		}
		if _, err := w.Write(b); err != nil {
			return err
		}
	}
	return nil
}

func (t *TokenAmount) UnmarshalCBOR(r io.Reader) error {
	*t = TokenAmount{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Atto (big.Int) (struct)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if maj != cbg.MajTag || extra != 2 {
		return fmt.Errorf("big ints should be cbor bignums")
	}

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if maj != cbg.MajByteString {
		return fmt.Errorf("big ints should be tagged cbor byte strings")
	}

	if extra > 256 {
		return fmt.Errorf("t.Atto: cbor bignum was too large")
	}

	if extra > 0 {
		buf := make([]byte, extra)
		if _, err := io.ReadFull(br, buf); err != nil {
			return err
		}
		t.Atto = big.NewInt(0).SetBytes(buf)
	} else {
		t.Atto = big.NewInt(0)
	}
	return nil
}

var lengthBufIPCSubnetActorState = []byte{143}

func (t *IPCSubnetActorState) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufIPCSubnetActorState); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Name (string) (string)
	if len(t.Name) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.Name was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.Name))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.Name)); err != nil {
		return err
	}

	// t.ParentID (ipc_types.SubnetID) (struct)
	if err := t.ParentID.MarshalCBOR(w); err != nil {
		return err
	}

	// t.IpcGatewayAddr (address.Address) (struct)
	if err := t.IpcGatewayAddr.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Consensus (ipc_types.ConsensusType) (int64)
	if t.Consensus >= 0 {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Consensus)); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.Consensus-1)); err != nil {
			return err
		}
	}

	// t.MinValidatorStake (ipc_types.TokenAmount) (struct)
	if err := t.MinValidatorStake.MarshalCBOR(w); err != nil {
		return err
	}

	// t.TotalStake (ipc_types.TokenAmount) (struct)
	if err := t.TotalStake.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Stake (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.Stake); err != nil {
		return xerrors.Errorf("failed to write cid field t.Stake: %w", err)
	}

	// t.Status (ipc_types.Status) (int64)
	if t.Status >= 0 {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Status)); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.Status-1)); err != nil {
			return err
		}
	}

	// t.Genesis ([]uint8) (slice)
	if len(t.Genesis) > cbg.ByteArrayMaxLen {
		return xerrors.Errorf("Byte array in field t.Genesis was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajByteString, uint64(len(t.Genesis))); err != nil {
		return err
	}

	if _, err := w.Write(t.Genesis[:]); err != nil {
		return err
	}

	// t.FinalityThreshold (ipc_types.ChainEpoch) (int64)
	if t.FinalityThreshold >= 0 {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.FinalityThreshold)); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.FinalityThreshold-1)); err != nil {
			return err
		}
	}

	// t.CheckPeriod (ipc_types.ChainEpoch) (int64)
	if t.CheckPeriod >= 0 {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.CheckPeriod)); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.CheckPeriod-1)); err != nil {
			return err
		}
	}

	// t.Checkpoints (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.Checkpoints); err != nil {
		return xerrors.Errorf("failed to write cid field t.Checkpoints: %w", err)
	}

	// t.WindowChecks (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.WindowChecks); err != nil {
		return xerrors.Errorf("failed to write cid field t.WindowChecks: %w", err)
	}

	// t.ValidatorSet ([]ipc_types.Validator) (slice)
	if len(t.ValidatorSet) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.ValidatorSet was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.ValidatorSet))); err != nil {
		return err
	}
	for _, v := range t.ValidatorSet {
		if err := v.MarshalCBOR(w); err != nil {
			return err
		}
	}

	// t.MinValidators (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.MinValidators)); err != nil {
		return err
	}

	return nil
}

func (t *IPCSubnetActorState) UnmarshalCBOR(r io.Reader) error {
	*t = IPCSubnetActorState{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 15 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Name (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.Name = string(sval)
	}
	// t.ParentID (ipc_types.SubnetID) (struct)

	{

		if err := t.ParentID.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.ParentID: %w", err)
		}

	}
	// t.IpcGatewayAddr (address.Address) (struct)

	{

		if err := t.IpcGatewayAddr.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.IpcGatewayAddr: %w", err)
		}

	}
	// t.Consensus (ipc_types.ConsensusType) (int64)
	{
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.Consensus = ConsensusType(extraI)
	}
	// t.MinValidatorStake (ipc_types.TokenAmount) (struct)

	{

		if err := t.MinValidatorStake.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.MinValidatorStake: %w", err)
		}

	}
	// t.TotalStake (ipc_types.TokenAmount) (struct)

	{

		if err := t.TotalStake.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.TotalStake: %w", err)
		}

	}
	// t.Stake (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.Stake: %w", err)
		}

		t.Stake = c

	}
	// t.Status (ipc_types.Status) (int64)
	{
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.Status = Status(extraI)
	}
	// t.Genesis ([]uint8) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.ByteArrayMaxLen {
		return fmt.Errorf("t.Genesis: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Genesis = make([]uint8, extra)
	}

	if _, err := io.ReadFull(br, t.Genesis[:]); err != nil {
		return err
	}
	// t.FinalityThreshold (ipc_types.ChainEpoch) (int64)
	{
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.FinalityThreshold = ChainEpoch(extraI)
	}
	// t.CheckPeriod (ipc_types.ChainEpoch) (int64)
	{
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.CheckPeriod = ChainEpoch(extraI)
	}
	// t.Checkpoints (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.Checkpoints: %w", err)
		}

		t.Checkpoints = c

	}
	// t.WindowChecks (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.WindowChecks: %w", err)
		}

		t.WindowChecks = c

	}
	// t.ValidatorSet ([]ipc_types.Validator) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("t.ValidatorSet: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.ValidatorSet = make([]Validator, extra)
	}

	for i := 0; i < int(extra); i++ {

		var v Validator
		if err := v.UnmarshalCBOR(br); err != nil {
			return err
		}

		t.ValidatorSet[i] = v
	}

	// t.MinValidators (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.MinValidators = uint64(extra)

	}
	return nil
}

var lengthBufConstructParams = []byte{137}

func (t *ConstructParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufConstructParams); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Parent (ipc_types.SubnetID) (struct)
	if err := t.Parent.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Name (string) (string)
	if len(t.Name) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.Name was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.Name))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.Name)); err != nil {
		return err
	}

	// t.IpcGatewayAddr (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.IpcGatewayAddr)); err != nil {
		return err
	}

	// t.Consensus (ipc_types.ConsensusType) (int64)
	if t.Consensus >= 0 {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Consensus)); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.Consensus-1)); err != nil {
			return err
		}
	}

	// t.MinValidatorStake (ipc_types.TokenAmount) (struct)
	if err := t.MinValidatorStake.MarshalCBOR(w); err != nil {
		return err
	}

	// t.MinValidators (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.MinValidators)); err != nil {
		return err
	}

	// t.FinalityThreshold (ipc_types.ChainEpoch) (int64)
	if t.FinalityThreshold >= 0 {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.FinalityThreshold)); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.FinalityThreshold-1)); err != nil {
			return err
		}
	}

	// t.CheckPeriod (ipc_types.ChainEpoch) (int64)
	if t.CheckPeriod >= 0 {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.CheckPeriod)); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.CheckPeriod-1)); err != nil {
			return err
		}
	}

	// t.Genesis ([]uint8) (slice)
	if len(t.Genesis) > cbg.ByteArrayMaxLen {
		return xerrors.Errorf("Byte array in field t.Genesis was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajByteString, uint64(len(t.Genesis))); err != nil {
		return err
	}

	if _, err := w.Write(t.Genesis[:]); err != nil {
		return err
	}
	return nil
}

func (t *ConstructParams) UnmarshalCBOR(r io.Reader) error {
	*t = ConstructParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 9 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Parent (ipc_types.SubnetID) (struct)

	{

		if err := t.Parent.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Parent: %w", err)
		}

	}
	// t.Name (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.Name = string(sval)
	}
	// t.IpcGatewayAddr (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.IpcGatewayAddr = uint64(extra)

	}
	// t.Consensus (ipc_types.ConsensusType) (int64)
	{
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.Consensus = ConsensusType(extraI)
	}
	// t.MinValidatorStake (ipc_types.TokenAmount) (struct)

	{

		if err := t.MinValidatorStake.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.MinValidatorStake: %w", err)
		}

	}
	// t.MinValidators (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.MinValidators = uint64(extra)

	}
	// t.FinalityThreshold (ipc_types.ChainEpoch) (int64)
	{
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.FinalityThreshold = ChainEpoch(extraI)
	}
	// t.CheckPeriod (ipc_types.ChainEpoch) (int64)
	{
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.CheckPeriod = ChainEpoch(extraI)
	}
	// t.Genesis ([]uint8) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.ByteArrayMaxLen {
		return fmt.Errorf("t.Genesis: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Genesis = make([]uint8, extra)
	}

	if _, err := io.ReadFull(br, t.Genesis[:]); err != nil {
		return err
	}
	return nil
}

var lengthBufJoinParams = []byte{129}

func (t *JoinParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufJoinParams); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.ValidatorNetAddr (string) (string)
	if len(t.ValidatorNetAddr) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.ValidatorNetAddr was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.ValidatorNetAddr))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.ValidatorNetAddr)); err != nil {
		return err
	}
	return nil
}

func (t *JoinParams) UnmarshalCBOR(r io.Reader) error {
	*t = JoinParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.ValidatorNetAddr (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.ValidatorNetAddr = string(sval)
	}
	return nil
}

var lengthBufVotes = []byte{129}

func (t *Votes) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufVotes); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Validators ([]address.Address) (slice)
	if len(t.Validators) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.Validators was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Validators))); err != nil {
		return err
	}
	for _, v := range t.Validators {
		if err := v.MarshalCBOR(w); err != nil {
			return err
		}
	}
	return nil
}

func (t *Votes) UnmarshalCBOR(r io.Reader) error {
	*t = Votes{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Validators ([]address.Address) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("t.Validators: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Validators = make([]address.Address, extra)
	}

	for i := 0; i < int(extra); i++ {

		var v address.Address
		if err := v.UnmarshalCBOR(br); err != nil {
			return err
		}

		t.Validators[i] = v
	}

	return nil
}

var lengthBufCheckpoint = []byte{130}

func (t *Checkpoint) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufCheckpoint); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Data (ipc_types.CheckData) (struct)
	if err := t.Data.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Sig ([]uint8) (slice)
	if len(t.Sig) > cbg.ByteArrayMaxLen {
		return xerrors.Errorf("Byte array in field t.Sig was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajByteString, uint64(len(t.Sig))); err != nil {
		return err
	}

	if _, err := w.Write(t.Sig[:]); err != nil {
		return err
	}
	return nil
}

func (t *Checkpoint) UnmarshalCBOR(r io.Reader) error {
	*t = Checkpoint{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Data (ipc_types.CheckData) (struct)

	{

		if err := t.Data.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Data: %w", err)
		}

	}
	// t.Sig ([]uint8) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.ByteArrayMaxLen {
		return fmt.Errorf("t.Sig: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Sig = make([]uint8, extra)
	}

	if _, err := io.ReadFull(br, t.Sig[:]); err != nil {
		return err
	}
	return nil
}

var lengthBufCheckData = []byte{134}

func (t *CheckData) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufCheckData); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Source (ipc_types.SubnetID) (struct)
	if err := t.Source.MarshalCBOR(w); err != nil {
		return err
	}

	// t.TipSet ([]uint8) (slice)
	if len(t.TipSet) > cbg.ByteArrayMaxLen {
		return xerrors.Errorf("Byte array in field t.TipSet was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajByteString, uint64(len(t.TipSet))); err != nil {
		return err
	}

	if _, err := w.Write(t.TipSet[:]); err != nil {
		return err
	}

	// t.Epoch (ipc_types.ChainEpoch) (int64)
	if t.Epoch >= 0 {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Epoch)); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.Epoch-1)); err != nil {
			return err
		}
	}

	// t.PrevCheck (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.PrevCheck); err != nil {
		return xerrors.Errorf("failed to write cid field t.PrevCheck: %w", err)
	}

	// t.Children ([]ipc_types.ChildCheck) (slice)
	if len(t.Children) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.Children was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Children))); err != nil {
		return err
	}
	for _, v := range t.Children {
		if err := v.MarshalCBOR(w); err != nil {
			return err
		}
	}

	// t.CrossMsgs ([]ipc_types.CrossMsgMeta) (slice)
	if len(t.CrossMsgs) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.CrossMsgs was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.CrossMsgs))); err != nil {
		return err
	}
	for _, v := range t.CrossMsgs {
		if err := v.MarshalCBOR(w); err != nil {
			return err
		}
	}
	return nil
}

func (t *CheckData) UnmarshalCBOR(r io.Reader) error {
	*t = CheckData{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 6 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Source (ipc_types.SubnetID) (struct)

	{

		if err := t.Source.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Source: %w", err)
		}

	}
	// t.TipSet ([]uint8) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.ByteArrayMaxLen {
		return fmt.Errorf("t.TipSet: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.TipSet = make([]uint8, extra)
	}

	if _, err := io.ReadFull(br, t.TipSet[:]); err != nil {
		return err
	}
	// t.Epoch (ipc_types.ChainEpoch) (int64)
	{
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.Epoch = ChainEpoch(extraI)
	}
	// t.PrevCheck (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.PrevCheck: %w", err)
		}

		t.PrevCheck = c

	}
	// t.Children ([]ipc_types.ChildCheck) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("t.Children: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Children = make([]ChildCheck, extra)
	}

	for i := 0; i < int(extra); i++ {

		var v ChildCheck
		if err := v.UnmarshalCBOR(br); err != nil {
			return err
		}

		t.Children[i] = v
	}

	// t.CrossMsgs ([]ipc_types.CrossMsgMeta) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("t.CrossMsgs: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.CrossMsgs = make([]CrossMsgMeta, extra)
	}

	for i := 0; i < int(extra); i++ {

		var v CrossMsgMeta
		if err := v.UnmarshalCBOR(br); err != nil {
			return err
		}

		t.CrossMsgs[i] = v
	}

	return nil
}

var lengthBufChildCheck = []byte{130}

func (t *ChildCheck) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufChildCheck); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Source (ipc_types.SubnetID) (struct)
	if err := t.Source.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Checks (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.Checks); err != nil {
		return xerrors.Errorf("failed to write cid field t.Checks: %w", err)
	}

	return nil
}

func (t *ChildCheck) UnmarshalCBOR(r io.Reader) error {
	*t = ChildCheck{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Source (ipc_types.SubnetID) (struct)

	{

		if err := t.Source.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Source: %w", err)
		}

	}
	// t.Checks (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.Checks: %w", err)
		}

		t.Checks = c

	}
	return nil
}

var lengthBufCrossMsgMeta = []byte{133}

func (t *CrossMsgMeta) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufCrossMsgMeta); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.From (ipc_types.SubnetID) (struct)
	if err := t.From.MarshalCBOR(w); err != nil {
		return err
	}

	// t.To (ipc_types.SubnetID) (struct)
	if err := t.To.MarshalCBOR(w); err != nil {
		return err
	}

	// t.MsgsCID (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.MsgsCID); err != nil {
		return xerrors.Errorf("failed to write cid field t.MsgsCID: %w", err)
	}

	// t.Nonce (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Nonce)); err != nil {
		return err
	}

	// t.Value (ipc_types.TokenAmount) (struct)
	if err := t.Value.MarshalCBOR(w); err != nil {
		return err
	}
	return nil
}

func (t *CrossMsgMeta) UnmarshalCBOR(r io.Reader) error {
	*t = CrossMsgMeta{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 5 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.From (ipc_types.SubnetID) (struct)

	{

		if err := t.From.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.From: %w", err)
		}

	}
	// t.To (ipc_types.SubnetID) (struct)

	{

		if err := t.To.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.To: %w", err)
		}

	}
	// t.MsgsCID (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.MsgsCID: %w", err)
		}

		t.MsgsCID = c

	}
	// t.Nonce (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Nonce = uint64(extra)

	}
	// t.Value (ipc_types.TokenAmount) (struct)

	{

		if err := t.Value.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Value: %w", err)
		}

	}
	return nil
}

var lengthBufIPCGatewayState = []byte{140}

func (t *IPCGatewayState) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufIPCGatewayState); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.NetworkName (ipc_types.SubnetID) (struct)
	if err := t.NetworkName.MarshalCBOR(w); err != nil {
		return err
	}

	// t.TotalSubnets (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.TotalSubnets)); err != nil {
		return err
	}

	// t.MinStake (ipc_types.TokenAmount) (struct)
	if err := t.MinStake.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Subnets (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.Subnets); err != nil {
		return xerrors.Errorf("failed to write cid field t.Subnets: %w", err)
	}

	// t.CheckPeriod (ipc_types.ChainEpoch) (int64)
	if t.CheckPeriod >= 0 {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.CheckPeriod)); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.CheckPeriod-1)); err != nil {
			return err
		}
	}

	// t.Checkpoints (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.Checkpoints); err != nil {
		return xerrors.Errorf("failed to write cid field t.Checkpoints: %w", err)
	}

	// t.CheckMsgRegistry (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.CheckMsgRegistry); err != nil {
		return xerrors.Errorf("failed to write cid field t.CheckMsgRegistry: %w", err)
	}

	// t.Nonce (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Nonce)); err != nil {
		return err
	}

	// t.BottomupNonce (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.BottomupNonce)); err != nil {
		return err
	}

	// t.BottomupMsgMeta (cid.Cid) (struct)

	if err := cbg.WriteCidBuf(scratch, w, t.BottomupMsgMeta); err != nil {
		return xerrors.Errorf("failed to write cid field t.BottomupMsgMeta: %w", err)
	}

	// t.AppliedBottomupNonce (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.AppliedBottomupNonce)); err != nil {
		return err
	}

	// t.AppliedTopdownNonce (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.AppliedTopdownNonce)); err != nil {
		return err
	}

	return nil
}

func (t *IPCGatewayState) UnmarshalCBOR(r io.Reader) error {
	*t = IPCGatewayState{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 12 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.NetworkName (ipc_types.SubnetID) (struct)

	{

		if err := t.NetworkName.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.NetworkName: %w", err)
		}

	}
	// t.TotalSubnets (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.TotalSubnets = uint64(extra)

	}
	// t.MinStake (ipc_types.TokenAmount) (struct)

	{

		if err := t.MinStake.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.MinStake: %w", err)
		}

	}
	// t.Subnets (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.Subnets: %w", err)
		}

		t.Subnets = c

	}
	// t.CheckPeriod (ipc_types.ChainEpoch) (int64)
	{
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.CheckPeriod = ChainEpoch(extraI)
	}
	// t.Checkpoints (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.Checkpoints: %w", err)
		}

		t.Checkpoints = c

	}
	// t.CheckMsgRegistry (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.CheckMsgRegistry: %w", err)
		}

		t.CheckMsgRegistry = c

	}
	// t.Nonce (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Nonce = uint64(extra)

	}
	// t.BottomupNonce (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.BottomupNonce = uint64(extra)

	}
	// t.BottomupMsgMeta (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(br)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.BottomupMsgMeta: %w", err)
		}

		t.BottomupMsgMeta = c

	}
	// t.AppliedBottomupNonce (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.AppliedBottomupNonce = uint64(extra)

	}
	// t.AppliedTopdownNonce (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.AppliedTopdownNonce = uint64(extra)

	}
	return nil
}

var lengthBufConstructorParams = []byte{130}

func (t *ConstructorParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufConstructorParams); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.NetworkName (string) (string)
	if len(t.NetworkName) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.NetworkName was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.NetworkName))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.NetworkName)); err != nil {
		return err
	}

	// t.CheckpointPeriod (ipc_types.ChainEpoch) (int64)
	if t.CheckpointPeriod >= 0 {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.CheckpointPeriod)); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.CheckpointPeriod-1)); err != nil {
			return err
		}
	}
	return nil
}

func (t *ConstructorParams) UnmarshalCBOR(r io.Reader) error {
	*t = ConstructorParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.NetworkName (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.NetworkName = string(sval)
	}
	// t.CheckpointPeriod (ipc_types.ChainEpoch) (int64)
	{
		maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return err
		}
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.CheckpointPeriod = ChainEpoch(extraI)
	}
	return nil
}

var lengthBufStorableMsg = []byte{134}

func (t *StorableMsg) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufStorableMsg); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.From (ipc_types.IPCAddress) (struct)
	if err := t.From.MarshalCBOR(w); err != nil {
		return err
	}

	// t.To (ipc_types.IPCAddress) (struct)
	if err := t.To.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Method (ipc_types.MethodNum) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Method)); err != nil {
		return err
	}

	// t.Params (ipc_types.RawBytes) (struct)
	if err := t.Params.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Value (ipc_types.TokenAmount) (struct)
	if err := t.Value.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Nonce (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Nonce)); err != nil {
		return err
	}

	return nil
}

func (t *StorableMsg) UnmarshalCBOR(r io.Reader) error {
	*t = StorableMsg{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 6 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.From (ipc_types.IPCAddress) (struct)

	{

		if err := t.From.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.From: %w", err)
		}

	}
	// t.To (ipc_types.IPCAddress) (struct)

	{

		if err := t.To.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.To: %w", err)
		}

	}
	// t.Method (ipc_types.MethodNum) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Method = MethodNum(extra)

	}
	// t.Params (ipc_types.RawBytes) (struct)

	{

		if err := t.Params.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Params: %w", err)
		}

	}
	// t.Value (ipc_types.TokenAmount) (struct)

	{

		if err := t.Value.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Value: %w", err)
		}

	}
	// t.Nonce (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Nonce = uint64(extra)

	}
	return nil
}

var lengthBufRawBytes = []byte{129}

func (t *RawBytes) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufRawBytes); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Bytes ([]uint8) (slice)
	if len(t.Bytes) > cbg.ByteArrayMaxLen {
		return xerrors.Errorf("Byte array in field t.Bytes was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajByteString, uint64(len(t.Bytes))); err != nil {
		return err
	}

	if _, err := w.Write(t.Bytes[:]); err != nil {
		return err
	}
	return nil
}

func (t *RawBytes) UnmarshalCBOR(r io.Reader) error {
	*t = RawBytes{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Bytes ([]uint8) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.ByteArrayMaxLen {
		return fmt.Errorf("t.Bytes: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Bytes = make([]uint8, extra)
	}

	if _, err := io.ReadFull(br, t.Bytes[:]); err != nil {
		return err
	}
	return nil
}

var lengthBufCrossMsg = []byte{130}

func (t *CrossMsg) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufCrossMsg); err != nil {
		return err
	}

	// t.Msg (ipc_types.StorableMsg) (struct)
	if err := t.Msg.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Wrapped (bool) (bool)
	if err := cbg.WriteBool(w, t.Wrapped); err != nil {
		return err
	}
	return nil
}

func (t *CrossMsg) UnmarshalCBOR(r io.Reader) error {
	*t = CrossMsg{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Msg (ipc_types.StorableMsg) (struct)

	{

		if err := t.Msg.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Msg: %w", err)
		}

	}
	// t.Wrapped (bool) (bool)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajOther {
		return fmt.Errorf("booleans must be major type 7")
	}
	switch extra {
	case 20:
		t.Wrapped = false
	case 21:
		t.Wrapped = true
	default:
		return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
	}
	return nil
}

var lengthBufFundParams = []byte{129}

func (t *FundParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufFundParams); err != nil {
		return err
	}

	// t.Value (ipc_types.TokenAmount) (struct)
	if err := t.Value.MarshalCBOR(w); err != nil {
		return err
	}
	return nil
}

func (t *FundParams) UnmarshalCBOR(r io.Reader) error {
	*t = FundParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Value (ipc_types.TokenAmount) (struct)

	{

		if err := t.Value.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Value: %w", err)
		}

	}
	return nil
}

var lengthBufCrossMsgParams = []byte{130}

func (t *CrossMsgParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufCrossMsgParams); err != nil {
		return err
	}

	// t.CrossMsg (ipc_types.CrossMsg) (struct)
	if err := t.CrossMsg.MarshalCBOR(w); err != nil {
		return err
	}

	// t.Destination (ipc_types.SubnetID) (struct)
	if err := t.Destination.MarshalCBOR(w); err != nil {
		return err
	}
	return nil
}

func (t *CrossMsgParams) UnmarshalCBOR(r io.Reader) error {
	*t = CrossMsgParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.CrossMsg (ipc_types.CrossMsg) (struct)

	{

		if err := t.CrossMsg.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.CrossMsg: %w", err)
		}

	}
	// t.Destination (ipc_types.SubnetID) (struct)

	{

		if err := t.Destination.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.Destination: %w", err)
		}

	}
	return nil
}

var lengthBufApplyMsgParams = []byte{129}

func (t *ApplyMsgParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufApplyMsgParams); err != nil {
		return err
	}

	// t.CrossMsg (ipc_types.CrossMsg) (struct)
	if err := t.CrossMsg.MarshalCBOR(w); err != nil {
		return err
	}
	return nil
}

func (t *ApplyMsgParams) UnmarshalCBOR(r io.Reader) error {
	*t = ApplyMsgParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.CrossMsg (ipc_types.CrossMsg) (struct)

	{

		if err := t.CrossMsg.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.CrossMsg: %w", err)
		}

	}
	return nil
}

var lengthBufCrossMsgs = []byte{130}

func (t *CrossMsgs) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufCrossMsgs); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Msgs ([]ipc_types.CrossMsg) (slice)
	if len(t.Msgs) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.Msgs was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Msgs))); err != nil {
		return err
	}
	for _, v := range t.Msgs {
		if err := v.MarshalCBOR(w); err != nil {
			return err
		}
	}

	// t.Metas ([]ipc_types.CrossMsgMeta) (slice)
	if len(t.Metas) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.Metas was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Metas))); err != nil {
		return err
	}
	for _, v := range t.Metas {
		if err := v.MarshalCBOR(w); err != nil {
			return err
		}
	}
	return nil
}

func (t *CrossMsgs) UnmarshalCBOR(r io.Reader) error {
	*t = CrossMsgs{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Msgs ([]ipc_types.CrossMsg) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("t.Msgs: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Msgs = make([]CrossMsg, extra)
	}

	for i := 0; i < int(extra); i++ {

		var v CrossMsg
		if err := v.UnmarshalCBOR(br); err != nil {
			return err
		}

		t.Msgs[i] = v
	}

	// t.Metas ([]ipc_types.CrossMsgMeta) (slice)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("t.Metas: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Metas = make([]CrossMsgMeta, extra)
	}

	for i := 0; i < int(extra); i++ {

		var v CrossMsgMeta
		if err := v.UnmarshalCBOR(br); err != nil {
			return err
		}

		t.Metas[i] = v
	}

	return nil
}
