// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package sdk

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufIPCAddress = []byte{130}

func (t *IPCAddress) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufIPCAddress); err != nil {
		return err
	}

	// t.SubnetID (sdk.SubnetID) (struct)
	if err := t.SubnetID.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.RawAddress (address.Address) (struct)
	if err := t.RawAddress.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *IPCAddress) UnmarshalCBOR(r io.Reader) (err error) {
	*t = IPCAddress{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.SubnetID (sdk.SubnetID) (struct)

	{

		if err := t.SubnetID.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.SubnetID: %w", err)
		}

	}
	// t.RawAddress (address.Address) (struct)

	{

		if err := t.RawAddress.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RawAddress: %w", err)
		}

	}
	return nil
}

var lengthBufSubnetID = []byte{130}

func (t *SubnetID) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufSubnetID); err != nil {
		return err
	}

	// t.Parent (string) (string)
	if len(t.Parent) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.Parent was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Parent))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.Parent)); err != nil {
		return err
	}

	// t.Actor (address.Address) (struct)
	if err := t.Actor.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *SubnetID) UnmarshalCBOR(r io.Reader) (err error) {
	*t = SubnetID{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Parent (string) (string)

	{
		sval, err := cbg.ReadString(cr)
		if err != nil {
			return err
		}

		t.Parent = string(sval)
	}
	// t.Actor (address.Address) (struct)

	{

		if err := t.Actor.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Actor: %w", err)
		}

	}
	return nil
}
