// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package sdk

import (
	"fmt"
	"io"
	"math"
	"sort"

	address "github.com/filecoin-project/go-address"
	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufIPCAddress = []byte{130}

func (t *IPCAddress) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufIPCAddress); err != nil {
		return err
	}

	// t.SubnetID (sdk.SubnetID) (struct)
	if err := t.SubnetID.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.RawAddress (address.Address) (struct)
	if err := t.RawAddress.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *IPCAddress) UnmarshalCBOR(r io.Reader) (err error) {
	*t = IPCAddress{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.SubnetID (sdk.SubnetID) (struct)

	{

		if err := t.SubnetID.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.SubnetID: %w", err)
		}

	}
	// t.RawAddress (address.Address) (struct)

	{

		if err := t.RawAddress.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.RawAddress: %w", err)
		}

	}
	return nil
}

var lengthBufSubnetID = []byte{130}

func (t *SubnetID) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufSubnetID); err != nil {
		return err
	}

	// t.Root (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Root)); err != nil {
		return err
	}

	// t.Children ([]address.Address) (slice)
	if len(t.Children) > cbg.MaxLength {
		return xerrors.Errorf("Slice value in field t.Children was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Children))); err != nil {
		return err
	}
	for _, v := range t.Children {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}
	}
	return nil
}

func (t *SubnetID) UnmarshalCBOR(r io.Reader) (err error) {
	*t = SubnetID{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Root (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Root = uint64(extra)

	}
	// t.Children ([]address.Address) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("t.Children: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Children = make([]address.Address, extra)
	}

	for i := 0; i < int(extra); i++ {

		var v address.Address
		if err := v.UnmarshalCBOR(cr); err != nil {
			return err
		}

		t.Children[i] = v
	}

	return nil
}
